version: "3.2"
services:
  localnode:
    image: "oasisdexorg/localnode:8d1909a8b7361993140b9bb9ab4a9144e40bdead"
    command: "master"
    ports:
      - "8545:8545"

  postgres:
    image: postgres
    container_name: postgres
    env_file:
      - $ENV_FILE
    ports:
      - "5432:5432"

  migrate:
    image: makerdao/vulcan0x
    container_name: migrate
    volumes:
      - $ENV_FILE:/opt/vulcan0x/.env
      - ./wait-for:/opt/vulcan0x/wait-for
      - ./../src:/opt/vulcan0x/src
      - ./../dapp:/opt/vulcan0x/dapp
      - ./../config:/opt/vulcan0x/config
    command: >
      bash -c "ENV=/opt/vulcan0x/.env ./wait-for postgres:5432 -t 30 && sleep 5 && npm run migrate"
    depends_on:
      - postgres
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 25s

  sync:
    image: makerdao/vulcan0x
    container_name: sync
    volumes:
      - $ENV_FILE:/opt/vulcan0x/.env
      - ./wait-for:/opt/vulcan0x/wait-for
      - ./../src:/opt/vulcan0x/src
      - ./../dapp:/opt/vulcan0x/dapp
      - ./../config:/opt/vulcan0x/config
    command: >
      bash -c "ENV=/opt/vulcan0x/.env ./wait-for postgres:5432 -t 30 && sleep 5 && npm run sync"
    depends_on:
      - postgres
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 25s
  # subscribe:
  #   image: makerdao/vulcan0x
  #   container_name: subscribe
  #   volumes:
  #     - $ENV_FILE:/opt/vulcan0x/.env
  #     - ./wait-for:/opt/vulcan0x/wait-for
  #     - ./../src:/opt/vulcan0x/src
  #     - ./../dapp:/opt/vulcan0x/dapp
  #     - ./../config:/opt/vulcan0x/config
  #   command: >
  #     bash -c "ENV=/opt/vulcan0x/.env ./wait-for postgres:5432 -t 30  && sleep 5 && npm run subscribe"
  #   depends_on:
  #     - postgres
  # graphql:
  #   image: makerdao/vulcan0x
  #   container_name: graphql
  #   ports:
  #     - 4000:4000
  #   volumes:
  #     - $ENV_FILE:/opt/vulcan0x/.env
  #     - ./wait-for:/opt/vulcan0x/wait-for
  #     - ./../graphql:/opt/vulcan0x/graphql
  #     - ./../config:/opt/vulcan0x/config
  #   command: >
  #     bash -c "ENV=/opt/vulcan0x/.env ./wait-for postgres:5432 -t 30 && sleep 10 && npm run graphql"
  #   depends_on:
  #     - migrate
