version: "3.2"
services:
  postgres:
    image: postgres
    container_name: postgres
    env_file:
      - $ENV_FILE
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./../pg/migrate:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"

  migrate:
    image: makerdao/vulcan0x
    container_name: migrate
    volumes:
      - $ENV_FILE:/opt/vulcan0x/.env
      - ./../src:/opt/vulcan0x/src
      - ./../config:/opt/vulcan0x/config
    command: >
      bash -c "ENV=/opt/vulcan0x/.env npm run migrate"
    depends_on:
      - postgres
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 25s

  sync:
    image: makerdao/vulcan0x
    container_name: sync
    volumes:
      - $ENV_FILE:/opt/vulcan0x/.env
      - ./../src:/opt/vulcan0x/src
      - ./../config:/opt/vulcan0x/config
    command: >
      bash -c "ENV=/opt/vulcan0x/.env npm run sync"
    depends_on:
      - postgres
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 25s

  subscribe:
    image: makerdao/vulcan0x
    container_name: subscribe
    volumes:
      - $ENV_FILE:/opt/vulcan0x/.env
      - ./../src:/opt/vulcan0x/src
      - ./../config:/opt/vulcan0x/config
    command: >
      bash -c "ENV=/opt/vulcan0x/.env npm run subscribe"
    depends_on:
      - postgres

  graphql:
    image: makerdao/vulcan0x
    container_name: graphql
    ports:
      - 4000:4000
    volumes:
      - $ENV_FILE:/opt/vulcan0x/.env
      - ./../graphql:/opt/vulcan0x/graphql
      - ./../config:/opt/vulcan0x/config
    command: >
      bash -c "ENV=/opt/vulcan0x/.env npm run graphql"
    depends_on:
      - postgres
