sudo: required
language: python
services:
- docker
before_install:
- docker build -t makerdao/vulcan0x .
script:
 - "./test.sh"
deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: master
env:
  global:
  - secure: F3CF0A3uoBtc9JD1tRm+X92fgr+elhoxwXuXzKa1Nzk9AOuJLne/rtt9pYtNoBwk5sLSr+IKjfYDioO1SzWeLKM1tfuBPT/bAOiMVRMH8roVwB5rec24+MxUI+LR8sWYJl/0GyUmzumLIjGomWodSlemOc6qlIokcr1EcfYYyty6uNsvsaLffUEdjriSnBRTV0o/5dR4Shu1ZDd5gEcpIB59m9Fb0QOVHhUpa1v/xTao3V3M4EiHqlROa/eJ4RxzKVtlvY3bMAN/mwm3FsKcWOFpuw9LvaMIHBF67qnoS47kUjDGwa1oq5QVu7nuwkej0y4dbtYVHHtmXhIjKc7NsEAj9gvNYNvC8x/v3buWBiQo5ZkPbTAtlGO4Ea+FDbNcOUrA3M7XbIvjMRDIsuCYwpIgKu7dh4q3WZx0NR3VI/S8uRKoc1HngRIaL5cRq6hSFYhWo8yJcs6TidqnHpI0PbJHR8tn1RGx1T1Mz4OFTcTJw0HhPmAYmFNrcVEIn2UJGFUcjxD+/XLZlqg6VqPyM2T74jlBFNcSio9KyXYaVEaZKpQqvsRYV4Tq7XU1AuRsdnskIk36VqETKhjeyB84bE0Zyka/HqKdDuVYOEDRG5HtoV6cy1m17qKrei0Wwb3mcmAP4TmSK/j0RP8bTPhQyaG3OwAhBRPRDf6w1OCcXIw=
  - secure: gf7Dhbh29zt/g1h9S/B15/DP/FPgaHLPF8gP4q6F1PKImqJQQ+4f6b1Es4T6/iZyFW1ueTbXqLc8M7y2ve2bnn5smqr/uSkQ/vCF8i+lMDKcBDlKx5birCBiuZidcrHRYHj7GhwzxI0ykRFgK1Tfii1zmofQQ8UjHzYL4CPDrtlMe+M5mVG1c73fuCN19lI7CAN+MSPWxM3yA8duEMRYvt/hImxVMU6Zka1ePV0rZgJcY1ASLEEVH6An8ja0JpBqRxZ+0dpFO4cLafruYtWfl4uOHic1TO0p9jHwSXIyghqdnjtKeJ8xreG08nbhHZq8T9ToeIGE2KeQGu5x+MrdygV/lMDF54H0wpcbauzq60KmLo4AffLb3I9hEc/BG/HIa00ExybhOL0UyfYtlHHYvWnhdpMIdcgnlEEXCZ3N6tfh56v1y2U7oYNVENtlUnOpHzFjepBrIXhUp9siPPDu2YxSfwAYWvvNRSFbnvE+m35wM6JvHU7dKAxXPcrEeiRlly+9uhgfoz6s0Nl93OkKMRU1+EqJcMZyOlWiYGXZf2M2BZDucotaDCnfTC8TLqJsi9Dxl7DH2MC/xYpQPeiYIW1ckQOSP2y0sidIsKwB9zX/LhhGmVmbI64iELkjLOAQ1fDUxdGhgJqguji+XlyAfeMVZgauBxJZgMrNl90EfGQ=
