version: 2
jobs:
  build:
    machine:
      enabled: true
      image: circleci/classic:edge
      docker_layer_caching: true
    working_directory: /home/circleci/app
    steps:
      - checkout

      - run: ./.circleci/install-yarn.sh

      - restore_cache:
          key: v1-dep-{{ checksum "yarn.lock" }}

      - run:
          name: Install deps
          command: source /opt/circleci/.nvm/nvm.sh && yarn install --frozen-lockfile

      - save_cache:
          paths:
            - ./node_modules
            - ~/.cache
          key: v1-dep-{{ checksum "yarn.lock" }}

#      - run:
#          name: Run tests
#          command: source /opt/circleci/.nvm/nvm.sh && ./test.sh

      - run: |
          # it's easier to do this here instead of separate job to avoid problems with previously built docker image not accessible
          if [ "$CIRCLE_BRANCH" == "master" ]; then
            docker build -t oasisdexorg/vulcan0x .
            ./scripts/deploy.sh
          fi
